In [1]:
import pandas as pd

In [27]:
train_df, test_df = pd.read_csv('~/Tweet-Sentiment-Extraction-Data/train.csv').set_index('textID'),\
                    pd.read_csv('~/Tweet-Sentiment-Extraction-Data/test.csv').set_index('textID')

In [38]:
all_df = pd.concat([train_df, test_df], keys=['train', 'test'], 
                   names=['dataset'])\
                   .reset_index('dataset')

In [39]:
all_df

,dataset,text,selected_text,sentiment
textID,,,,
cb774db0d1,train,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
549e992a42,train,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
088c60f138,train,my boss is bullying me...,bullying me,negative
9642c003ef,train,what interview! leave me alone,leave me alone,negative
358bd9e861,train,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative
...,...,...,...,...
e5f0e6ef4b,test,"its at 3 am, im very tired but i can`t sleep ...",NaN,negative
416863ce47,test,All alone in this old house again. Thanks for...,NaN,positive
6332da480c,test,I know what you mean. My little dog is sinkin...,NaN,negative
df1baec676,test,_sutra what is your next youtube video gonna b...,NaN,positive
469e15c5a8,test,http://twitpic.com/4woj2 - omgssh ang cute n...,NaN,positive